/** English i18n keys for static marketing / support pages (spread into lib/i18n.ts `en`). */
export const staticPageEn = {
  // About Us
  'about.badge': 'India’s deal platform',
  'about.hero.title': 'Used vehicle deals, completed with clarity',
  'about.hero.subtitle':
    'Discover listings, open a private deal room, share documents, and track every milestone until RC transfer — all in one place.',
  'about.hero.ctaBuy': 'Browse cars',
  'about.hero.ctaSell': 'Sell your car',
  'about.trust1': 'RC on listings',
  'about.trust2': 'Tracked deal rooms',
  'about.trust3': 'Free to list',
  'about.stat1.label': 'India-first',
  'about.stat1.value': 'Pan-India',
  'about.stat2.label': 'End-to-end',
  'about.stat2.value': 'Deal → RC',
  'about.stat3.label': 'Forever free',
  'about.stat3.value': 'Free list',
  'about.whatWeDo.title': 'What we do',
  'about.whatWeDo.eyebrow': 'The platform',
  'about.whatWeDo.body':
    'ReRide helps buyers discover used vehicles with RC and seller details on listings. Each interested buyer can open a deal room to chat, negotiate offers, schedule inspection, and track token, delivery, and RC transfer steps. We are a technology platform — we do not buy your vehicle or guarantee its condition. Optional paid assistance is available for document review and RC coordination.',
  'about.whatWeDo.point1': 'Listings with RC & seller context',
  'about.whatWeDo.point2': 'Private deal rooms for serious buyers',
  'about.whatWeDo.point3': 'Milestones through to RC transfer',
  'about.why.title': 'Why people choose ReRide',
  'about.why.eyebrow': 'Built different',
  'about.feature1.title': 'Deal rooms, not dead ends',
  'about.feature1.desc': 'Every serious buyer gets a tracked deal — chat, offers, and documents in one place.',
  'about.feature2.title': 'Built for India',
  'about.feature2.desc': '₹ pricing, WhatsApp-friendly contact, and support channels people actually use.',
  'about.feature3.title': 'Trust through transparency',
  'about.feature3.desc': 'RC on listings, safety policies, and clear intermediary terms — no hidden aggregator playbook.',
  'about.contact.title': 'Questions or partnerships?',
  'about.contact.body': 'Reach us through Support or call {{phone}}. We reply to serious enquiries fast.',
  'about.contact.bodyNoPhone': 'Reach us through Support. We reply to serious enquiries fast.',
  'about.contact.cta': 'Talk to support',
  'about.howDeals.title': 'How a deal works',
  'about.howDeals.eyebrow': 'Simple path',
  'about.howDeals.subtitle': 'From first interest to RC transfer — every step tracked on ReRide.',
  'about.howDeals.step1.title': 'Interest',
  'about.howDeals.step1.tag': 'Discover',
  'about.howDeals.step1.desc': 'Browse listings with RC details and save vehicles you like.',
  'about.howDeals.step2.title': 'Chat & inspect',
  'about.howDeals.step2.tag': 'Deal room',
  'about.howDeals.step2.desc': 'Message the seller, schedule a test drive, and verify documents.',
  'about.howDeals.step3.title': 'RC transfer',
  'about.howDeals.step3.tag': 'Complete',
  'about.howDeals.step3.desc': 'Track offer, token, handover, and RC milestones in one place.',
  'about.notWe.title': 'What we are not',
  'about.notWe.body':
    'We are not an instant-buy aggregator, not the seller of vehicles on the platform, and not a bank or insurer. ReRide helps parties complete deals transparently — we do not guarantee vehicle condition.',

  // Safety Center
  'safety.badge': 'Trust & safety',
  'safety.hero.title': 'Stay in control, reduce risk',
  'safety.hero.subtitle':
    'Practical tips for buying, selling, and meeting on ReRide — so every deal stays safe and stress-free.',
  'safety.buying.title': 'Buying a used car',
  'safety.buying.tip1':
    'Inspect the vehicle in daylight; check service history, VIN, and RC where possible.',
  'safety.buying.tip2':
    'Prefer verified listings and clear photos; ask for an independent inspection if unsure.',
  'safety.buying.tip3':
    'Never pay full amounts upfront to strangers; use agreed milestones and documented transfers.',
  'safety.selling.title': 'Selling',
  'safety.selling.tip1': 'Meet buyers in safe, public places; consider bringing someone with you.',
  'safety.selling.tip2':
    'Share accurate condition and paperwork; misrepresentation hurts trust and can cause disputes.',
  'safety.selling.tip3': 'Confirm payment before handing over keys and documents.',
  'safety.scams.title': 'Scams & red flags',
  'safety.scams.tip1': 'Pressure to move off-platform, unusual payment apps, or “shipping only” deals.',
  'safety.scams.tip2': 'Prices far below market with excuses for no inspection or test drive.',
  'safety.scams.tip3': 'Requests for OTPs, passwords, or full card details over chat.',
  'safety.dealRoom.title': 'Inside a ReRide deal',
  'safety.dealRoom.tip1': 'Keep offers, inspection notes, and document uploads in the deal room — not scattered across WhatsApp only.',
  'safety.dealRoom.tip2': 'Use milestones (offer → token → handover → RC) so both sides know what is done and what is next.',
  'safety.dealRoom.tip3': 'Never share OTPs or pay the full vehicle amount before you have inspected the car and verified RC.',
  'safety.rc.title': 'RC transfer red flags',
  'safety.rc.tip1': 'Engine or chassis number on the vehicle does not match the RC or Parivahan record.',
  'safety.rc.tip2': 'Pending loan or hypothecation without a bank NOC; seller cannot produce original RC.',
  'safety.rc.tip3': 'Pressure to skip RTO formalities or transfer ownership only on a notarised paper.',
  'safety.help.title': 'Need help?',
  'safety.help.body':
    'Report suspicious behaviour from the listing or inbox, or contact Support. For emergencies, contact local authorities.',
  'safety.help.cta': 'Contact support',

  // Support
  'support.badge': 'Priority support that actually answers',
  'support.hero.title': 'Contact Support',
  'support.hero.subtitle':
    "Tell us what you need. We'll route your request to the right specialist and keep you posted every step of the way.",
  'support.stat.response': 'Avg. response under 30 mins',
  'support.stat.satisfaction': '4.8/5 satisfaction',
  'support.urgent.title': 'Need urgent help?',
  'support.urgent.body': 'We monitor tickets around the clock.',
  'support.card.badge': 'Fastest Resolution',
  'support.card.title': 'We pair every ticket with a specialist',
  'support.card.body':
    "Share a few details and we'll triage, prioritize, and keep you updated. 90% of tickets are resolved without a follow-up.",
  'support.category.service': 'Car service & detailing',
  'support.category.buySell': 'Buying & selling help',
  'support.category.payments': 'Payments & RC',
  'support.category.app': 'App issues',
  'support.quickReach.eyebrow': 'Quick reach',
  'support.quickReach.title': 'Prefer a faster lane?',
  'support.quickReach.call.title': 'Call us',
  'support.quickReach.call.desc': 'Mon-Sat, 9am-8pm',
  'support.quickReach.whatsapp.title': 'WhatsApp',
  'support.quickReach.whatsapp.desc': 'Quick status updates',
  'support.quickReach.email.title': 'Email',
  'support.quickReach.email.desc': 'support@reride.com',
  'support.quickReach.openMail': 'Open mail',
  'support.form.name': 'Your Name',
  'support.form.email': 'Your Email',
  'support.form.subject': 'Subject',
  'support.form.message': 'Message',
  'support.form.namePlaceholder': 'Enter your full name',
  'support.form.emailPlaceholder': 'your.email@example.com',
  'support.form.subjectPlaceholder': 'Brief description of your issue',
  'support.form.messagePlaceholder': 'Share more context to help us resolve this quickly...',
  'support.form.submit': 'Submit Ticket',
  'support.form.submitting': 'Submitting…',
  'support.success.title': 'Ticket submitted!',
  'support.success.body': "We've received your request and will reach out shortly.",

  // Sell Car (landing / step 0)
  'sellCar.hero.title': 'List your vehicle',
  'sellCar.hero.subtitle': 'Manage every buyer till RC transfer',
  'sellCar.step0.badge': 'Free listing · You set the price',
  'sellCar.step0.title': 'Sell with a clear deal room for every buyer',
  'sellCar.step0.subtitle':
    'Add RC, photos, and honest details. Accept buyer chats, track offers, inspection, and documents until handover.',
  'sellCar.trust.free.value': 'Free',
  'sellCar.trust.free.label': 'To list your vehicle',
  'sellCar.trust.direct.value': 'Direct',
  'sellCar.trust.direct.label': 'Buyer contact',
  'sellCar.trust.panIndia.value': 'Pan-India',
  'sellCar.trust.panIndia.label': 'City coverage',
  'sellCar.highlight1.title': 'Complete listing',
  'sellCar.highlight1.desc': 'RC, photos, and condition details buyers can verify.',
  'sellCar.highlight2.title': 'Organised buyers',
  'sellCar.highlight2.desc': 'Accept chats and manage each deal from your dashboard.',
  'sellCar.highlight3.title': 'Track to RC',
  'sellCar.highlight3.desc': 'Milestones for offer, token, delivery, and RC transfer.',
  'sellCar.step0.pickOne': 'Pick one to begin',
  'sellCar.step0.whoSelling': "Who's selling?",
  'sellCar.individual.title': 'Sell as Individual',
  'sellCar.individual.recommended': 'Recommended',
  'sellCar.individual.desc': 'List your personal vehicle and manage buyer deals in one place.',
  'sellCar.individual.tag1': 'Free listing',
  'sellCar.individual.tag2': 'Deal tracking',
  'sellCar.individual.tag3': 'RC checklist',
  'sellCar.dealer.title': 'Sell as Dealer',
  'sellCar.dealer.desc': 'Log in to your dealer account and manage inventory.',
  'sellCar.dealer.tag1': 'Bulk listing',
  'sellCar.dealer.tag2': 'Hot leads',
  'sellCar.dealer.tag3': 'Lead inbox',
  'sellCar.step0.help':
    'Need help? Call 727-727-7275 or chat with us — we answer in under 60 seconds.',
  'sellCar.back': 'Back',

  // Mobile Sell Car
  'sellCar.mobile.title': 'Sell Your Car',
  'sellCar.mobile.step0.title': 'I am a',
  'sellCar.mobile.individual.title': 'Individual',
  'sellCar.mobile.individual.desc': 'Selling my personal vehicle',
  'sellCar.mobile.dealer.title': 'Dealer',
  'sellCar.mobile.dealer.desc': 'I have a dealership',

  // Mobile Support
  'support.mobile.badge': 'Support',
  'support.mobile.hero.title': 'How can we help?',
  'support.mobile.hero.subtitle': 'Send us a ticket — we typically reply within a day.',
  'support.mobile.email.label': 'Email us',
  'support.mobile.form.eyebrow': 'New ticket',
  'support.mobile.form.title': "Tell us what's happening",
  'support.mobile.form.name': 'Name',
  'support.mobile.form.namePlaceholder': 'Your name',
  'support.mobile.form.messagePlaceholder': 'Describe your issue in detail...',
  'support.mobile.form.submit': 'Submit ticket',
  'support.mobile.success.title': 'Ticket submitted',
  'support.mobile.success.body': "We'll get back to you shortly.",
  'support.mobile.error.submit': 'Failed to submit support ticket. Please try again.',
  'support.mobile.validation.name': 'Name is required',
  'support.mobile.validation.email': 'Email is required',
  'support.mobile.validation.emailInvalid': 'Please enter a valid email address',
  'support.mobile.validation.subject': 'Subject is required',
  'support.mobile.validation.message': 'Message is required',

  // Service detail (UI chrome)
  'serviceDetail.back': 'Back to Services',
  'serviceDetail.included.title': 'Services Included',
  'serviceDetail.included.atCheckout': 'At checkout',
  'serviceDetail.why.title': 'Why Choose This Service?',
  'serviceDetail.quality.title': 'Service Quality Assured',
  'serviceDetail.quality.oem.title': 'OEM Parts Only',
  'serviceDetail.quality.oem.desc': 'Only OEM or brand-authorised parts used',
  'serviceDetail.quality.warranty.title': '3-Month Warranty',
  'serviceDetail.quality.warranty.desc': 'Service warranty on parts & workmanship',
  'serviceDetail.quality.updates.title': 'Real-Time Updates',
  'serviceDetail.quality.updates.desc': 'Track your service progress live',
  'serviceDetail.quality.photos.title': 'Pre & Post Photos',
  'serviceDetail.quality.photos.desc': 'Complete documentation of service',
  'serviceDetail.pricing.title': 'Pricing & Booking',
  'serviceDetail.pricing.finalLabel': 'Final price',
  'serviceDetail.pricing.confirmed': 'Price confirmed at checkout',
  'serviceDetail.pricing.body':
    "We'll match you with a nearby verified service provider based on your location. Final pricing may vary by provider, vehicle model, and pickup/drop preference.",
  'serviceDetail.pricing.typicalRange': 'Typical range',
  'serviceDetail.pricing.rangeHint': 'Estimated range only. Final price is shown before payment.',
  'serviceDetail.pricing.feature1': 'Final breakup before payment',
  'serviceDetail.pricing.feature2': '3-month warranty',
  'serviceDetail.pricing.feature3': 'Verified workshops',
  'serviceDetail.pricing.feature4': 'Doorstep pickup available',
  'serviceDetail.pricing.featureProvider': 'Provider selected based on location',
  'serviceDetail.pricing.featurePickup': 'Pickup & drop available',
  'serviceDetail.pricing.featureUpdates': 'Real-time updates',
  'serviceDetail.loading': 'Loading service details...',
  'serviceDetail.bookNow': 'Book Now',
  'serviceDetail.addToCart': 'Add to Cart',
  'serviceDetail.callForQuote': 'Call for Quote',
  'serviceDetail.contactSupport': 'Contact support',
  'serviceDetail.secure': 'Secure',
  'serviceDetail.verified': 'Verified',
} as const;
